"""report_perf.py — turn equity_curve.csv into a performance read.

trader.py appends a NAV point (timestamp,total_equity,cash,holdings) every run
via log_equity(). This script collapses that to a daily NAV series and reports
the metrics that tell you whether anything is actually working:

    total return, CAGR, annualised Sharpe, max drawdown, volatility,
    win rate, and total return vs SPY over the same window.

Always prints a metrics table and writes a self-contained HTML report
(report_perf.html) — no third-party dependency required. If `quantstats` is
installed it ALSO emits a full tear sheet (report_perf_quantstats.html).

Usage:  python3 report_perf.py [--csv equity_curve.csv] [--out report_perf.html]
"""

import argparse
from pathlib import Path

import numpy as np
import pandas as pd

DIR = Path(__file__).parent
TRADING_DAYS = 252


def load_daily_nav(csv_path: Path) -> pd.Series:
    """Read equity_curve.csv → one end-of-day NAV per calendar day."""
    df = pd.read_csv(csv_path, parse_dates=["timestamp"])
    df = df.dropna(subset=["timestamp", "total_equity"]).sort_values("timestamp")
    if df.empty:
        return pd.Series(dtype=float)
    df["day"] = df["timestamp"].dt.normalize()
    daily = df.groupby("day")["total_equity"].last()
    daily.index = pd.to_datetime(daily.index)
    return daily


def compute_metrics(nav: pd.Series) -> dict:
    ret   = nav.pct_change().dropna()
    days  = max((nav.index[-1] - nav.index[0]).days, 1)
    total = nav.iloc[-1] / nav.iloc[0] - 1
    cagr  = (nav.iloc[-1] / nav.iloc[0]) ** (365.0 / days) - 1 if nav.iloc[0] > 0 else float("nan")
    vol   = ret.std() * np.sqrt(TRADING_DAYS) if len(ret) > 1 else float("nan")
    sharpe = (ret.mean() / ret.std() * np.sqrt(TRADING_DAYS)
              if len(ret) > 1 and ret.std() > 0 else float("nan"))
    dd    = (nav / nav.cummax() - 1).min()
    winrt = (ret > 0).mean() if len(ret) else float("nan")
    return {
        "start":        nav.index[0].date().isoformat(),
        "end":          nav.index[-1].date().isoformat(),
        "days":         days,
        "points":       int(len(nav)),
        "start_equity": float(nav.iloc[0]),
        "end_equity":   float(nav.iloc[-1]),
        "total_return": float(total),
        "cagr":         float(cagr),
        "sharpe":       float(sharpe),
        "max_drawdown": float(dd),
        "volatility":   float(vol),
        "win_rate":     float(winrt),
    }


def spy_return(start: str, end: str):
    """Total SPY return over the window, via the resilient get_daily loader."""
    try:
        from data.history import get_daily
        end_incl = (pd.Timestamp(end) + pd.Timedelta(days=1)).strftime("%Y-%m-%d")
        spy = get_daily("SPY", start, end_incl)
        if spy is None or spy.empty:
            return None
        return float(spy["Close"].iloc[-1] / spy["Close"].iloc[0] - 1)
    except Exception:
        return None


def _pct(x) -> str:
    return "n/a" if x is None or (isinstance(x, float) and np.isnan(x)) else f"{x*100:+.2f}%"


def _num(x) -> str:
    return "n/a" if x is None or (isinstance(x, float) and np.isnan(x)) else f"{x:.2f}"


def render_html(m: dict, spy, out_path: Path) -> None:
    edge = None
    if spy is not None and not np.isnan(m["total_return"]):
        edge = m["total_return"] - spy
    rows = [
        ("Window",            f'{m["start"]} → {m["end"]}  ({m["days"]} days, {m["points"]} pts)'),
        ("Start / End NAV",   f'${m["start_equity"]:,.0f}  →  ${m["end_equity"]:,.0f}'),
        ("Total return",      _pct(m["total_return"])),
        ("CAGR",              _pct(m["cagr"])),
        ("Sharpe (annual)",   _num(m["sharpe"])),
        ("Max drawdown",      _pct(m["max_drawdown"])),
        ("Volatility (annual)", _pct(m["volatility"])),
        ("Win rate (daily)",  _pct(m["win_rate"])),
        ("SPY return (same window)", _pct(spy)),
        ("Edge vs SPY",       _pct(edge)),
    ]
    body = "\n".join(
        f'<tr><td class="k">{k}</td><td class="v">{v}</td></tr>' for k, v in rows
    )
    html = f"""<!doctype html><html><head><meta charset="utf-8">
<title>AI-Trader Performance</title><style>
body{{font-family:-apple-system,Segoe UI,Roboto,sans-serif;background:#0b1f3a;color:#e8eefc;margin:0;padding:2rem}}
h1{{font-size:1.3rem;margin:0 0 1rem}}
table{{border-collapse:collapse;min-width:420px}}
td{{padding:.55rem 1rem;border-bottom:1px solid #1c3a63}}
td.k{{color:#8fb0e0}} td.v{{text-align:right;font-variant-numeric:tabular-nums;font-weight:600}}
.note{{margin-top:1.2rem;color:#6f8fbf;font-size:.8rem}}
</style></head><body>
<h1>AI-Trader — Performance ({m["start"]} → {m["end"]})</h1>
<table>{body}</table>
<p class="note">Generated by report_perf.py from equity_curve.csv. Paper account — not investment advice.</p>
</body></html>"""
    out_path.write_text(html)


def try_quantstats(nav: pd.Series, spy_series_start: str, spy_series_end: str) -> str | None:
    try:
        import quantstats as qs
    except ImportError:
        return None
    try:
        returns = nav.pct_change().dropna()
        returns.index = pd.to_datetime(returns.index)
        bench = None
        try:
            from data.history import get_daily
            end_incl = (pd.Timestamp(spy_series_end) + pd.Timedelta(days=1)).strftime("%Y-%m-%d")
            spy = get_daily("SPY", spy_series_start, end_incl)
            if spy is not None and not spy.empty:
                bench = spy["Close"].pct_change().dropna()
        except Exception:
            bench = None
        out = DIR / "report_perf_quantstats.html"
        qs.reports.html(returns, benchmark=bench, output=str(out), title="AI-Trader")
        return str(out)
    except Exception:
        return None


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--csv", default=str(DIR / "equity_curve.csv"))
    ap.add_argument("--out", default=str(DIR / "report_perf.html"))
    args = ap.parse_args()

    csv_path = Path(args.csv)
    if not csv_path.exists():
        print(f"No equity curve yet: {csv_path}\n"
              f"Run trader.py at least twice on different days to build one.")
        return

    nav = load_daily_nav(csv_path)
    if len(nav) < 2:
        print(f"Only {len(nav)} daily NAV point(s) in {csv_path.name} — need >=2 to "
              f"compute returns. Let trader.py run across more days first.")
        return

    m   = compute_metrics(nav)
    spy = spy_return(m["start"], m["end"])

    print("\n" + "=" * 54)
    print("  AI-TRADER PERFORMANCE")
    print("=" * 54)
    print(f"  window        {m['start']} -> {m['end']}  ({m['days']}d, {m['points']} pts)")
    print(f"  NAV           ${m['start_equity']:,.0f} -> ${m['end_equity']:,.0f}")
    print(f"  total return  {_pct(m['total_return'])}")
    print(f"  CAGR          {_pct(m['cagr'])}")
    print(f"  Sharpe        {_num(m['sharpe'])}")
    print(f"  max drawdown  {_pct(m['max_drawdown'])}")
    print(f"  volatility    {_pct(m['volatility'])}")
    print(f"  win rate      {_pct(m['win_rate'])}")
    print(f"  SPY (window)  {_pct(spy)}")
    if spy is not None and not np.isnan(m["total_return"]):
        print(f"  edge vs SPY   {_pct(m['total_return'] - spy)}")
    print("=" * 54)

    out_path = Path(args.out)
    render_html(m, spy, out_path)
    print(f"  HTML report  -> {out_path}")

    qs_out = try_quantstats(nav, m["start"], m["end"])
    if qs_out:
        print(f"  QuantStats   -> {qs_out}")
    else:
        print("  (install `quantstats` for a full tear sheet)")


if __name__ == "__main__":
    main()
